"""empty message

Revision ID: a0f2d0ebb89a
Revises: b50dc2d0a1fd
Create Date: 2022-08-19 11:43:49.002915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f2d0ebb89a'
down_revision = 'b50dc2d0a1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('shows_venue_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_artist_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    op.drop_column('shows', 'artist')
    op.drop_column('shows', 'venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_artist_fkey', 'shows', 'Artist', ['artist'], ['id'])
    op.create_foreign_key('shows_venue_fkey', 'shows', 'Venue', ['venue'], ['id'])
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
