"""empty message

Revision ID: b50dc2d0a1fd
Revises: 93f95599a64f
Create Date: 2022-08-18 14:51:32.793759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50dc2d0a1fd'
down_revision = '93f95599a64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(), nullable=True))
    op.drop_column('shows', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('datetime', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
